load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")
load("@prelude//toolchains:go.bzl", "system_go_toolchain", "system_go_bootstrap_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("//mdbook:mdbook.bzl", "system_mdbook_toolchain")

# Explicit system toolchains for Rust, Go, Python, and C++
system_rust_toolchain(
    name = "rust",
    visibility = ["PUBLIC"],
)

system_go_toolchain(
    name = "go",
    visibility = ["PUBLIC"],
)

system_go_bootstrap_toolchain(
    name = "go_bootstrap",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_mdbook_toolchain(
    name = "mdbook",
    visibility = ["PUBLIC"],
)