{ config, pkgs, lib, ... }:

let
  # Script to generate Buck2 toolchain configuration
  generateBuck2Configs = pkgs.writeShellScriptBin "generate-buck2-configs" ''
    set -euo pipefail

    echo "🔧 Generating Buck2 toolchain configurations..."

    # Generate .buckconfig.toolchains with actual paths from the environment
    {
      echo "# Generated by devenv - DO NOT EDIT"
      echo "# This file is automatically generated when entering the development shell"
      echo "# Source: nix/devenv/buck2.nix"
      echo ""

      ${lib.optionalString config.languages.go.enable ''
      if command -v go &> /dev/null; then
        echo "[go]"
        echo "go = $(command -v go)"
        echo ""
      fi
      ''}

      ${lib.optionalString config.languages.rust.enable ''
      if command -v rustc &> /dev/null && command -v cargo &> /dev/null; then
        echo "[rust]"
        echo "rustc = $(command -v rustc)"
        echo "cargo = $(command -v cargo)"
        echo "rustc_action = $(command -v rustc)"
        echo ""
      fi
      ''}

      ${lib.optionalString config.languages.python.enable ''
      if command -v python3 &> /dev/null; then
        echo "[python]"
        echo "interpreter = $(command -v python3)"
        echo ""
      fi
      ''}

      ${lib.optionalString (config.languages.c.enable || config.languages.cplusplus.enable) ''
      if command -v clang &> /dev/null && command -v clang++ &> /dev/null; then
        echo "[cxx]"
        echo "cc = $(command -v clang)"
        echo "cxx = $(command -v clang++)"
        echo ""
      fi
      ''}
    } > .buckconfig.toolchains

    echo "✅ Generated .buckconfig.toolchains"

    # Verify synchronization
    echo ""
    echo "📊 Toolchain Verification:"
    ${lib.optionalString config.languages.go.enable ''
    if command -v go &> /dev/null; then
      echo "  Go:     $(command -v go)"
    fi
    ''}
    ${lib.optionalString config.languages.rust.enable ''
    if command -v rustc &> /dev/null; then
      echo "  Rust:   $(command -v rustc)"
    fi
    ''}
    ${lib.optionalString config.languages.python.enable ''
    if command -v python3 &> /dev/null; then
      echo "  Python: $(command -v python3)"
    fi
    ''}
    ${lib.optionalString (config.languages.c.enable || config.languages.cplusplus.enable) ''
    if command -v clang &> /dev/null; then
      echo "  Clang:  $(command -v clang)"
    fi
    ''}
    echo ""
  '';

in
{
  packages = [ generateBuck2Configs ];

  enterShell = ''
    # Auto-generate Buck2 configs on shell entry
    generate-buck2-configs
  '';
}
